/**
 * The shim half: a `ZDOTDIR` directory that makes every non-interactive zsh the
 * agent runs source the user's aliases and functions, without paying for
 * oh-my-zsh / compinit / autosuggestions / syntax-highlighting on each command.
 *
 * Layout (under `$XDG_STATE_HOME/opencode/shell-rc`):
 *   .zshenv     the shim zsh reads first; sources the real zshenv, then state.zsh
 *   state.zsh   generated from `zsh -ic 'alias -L; typeset -f'`, refreshed when
 *               the rc changes (never per command)
 *   .zshrc …    symlinks so nested `zsh -i` / login shells still find the real rc
 */
import { execFileSync } from "node:child_process";
import {
	existsSync,
	lstatSync,
	mkdirSync,
	readFileSync,
	renameSync,
	rmSync,
	statSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { LINKED } from "./constants/shell-rc";

/** Read `HOME` per call so tests can point it at a temp directory. */
const home = (): string => process.env.HOME ?? homedir();

export function stateDir(): string {
	const base = process.env.XDG_STATE_HOME ?? join(home(), ".local", "state");
	return join(base, "opencode", "shell-rc");
}

export function shimFile(): string {
	return join(stateDir(), ".zshenv");
}

export function stateFile(): string {
	return join(stateDir(), "state.zsh");
}

/**
 * The `.zshenv` every agent zsh sources. Deliberately tiny and side-effect free:
 * `$HOME/.zshenv` (which zsh would source anyway) first, then the generated
 * aliases/functions, then an optional user escape hatch.
 */
export function shimContent(): string {
	return [
		"# Generated by opencode-shell-rc. Sourced by every zsh the agent runs.",
		'[[ -f "$HOME/.zshenv" ]] && source "$HOME/.zshenv"',
		'[[ -n "$ZDOTDIR" && -f "$ZDOTDIR/state.zsh" ]] && source "$ZDOTDIR/state.zsh"',
		'[[ -f "$HOME/.config/opencode/shell.zsh" ]] && source "$HOME/.config/opencode/shell.zsh"',
		"",
	].join("\n");
}

export function isZsh(shell: string): boolean {
	return /(^|[\\/])zsh(\.exe)?$/.test(shell);
}

/** Existing rc files whose mtime the generated state depends on. */
export function sourceFiles(): string[] {
	return [
		join(home(), ".zshrc"),
		join(home(), ".zshenv"),
		join(home(), ".oh-my-zsh", "oh-my-zsh.sh"),
	].filter((file) => existsSync(file));
}

/** Pure staleness check so it can be tested without touching the filesystem. */
export function needsRefresh(
	stateMtime: number | undefined,
	sourceMtimes: number[],
): boolean {
	if (stateMtime === undefined) return true;
	return sourceMtimes.some((mtime) => mtime > stateMtime);
}

/**
 * Regenerate `state.zsh` iff the rc is newer (or the state is missing). Returns
 * whether it regenerated. Uses zsh's own serializer (`alias -L`, `typeset -f`)
 * so aliases and functions are captured exactly, including oh-my-zsh's.
 */
export function refreshIfStale(): boolean {
	const state = stateFile();
	const stateMtime = existsSync(state) ? statSync(state).mtimeMs : undefined;
	const sourceMtimes = sourceFiles().map((file) => statSync(file).mtimeMs);
	if (!needsRefresh(stateMtime, sourceMtimes)) return false;

	let output: string;
	try {
		output = execFileSync("zsh", ["-ic", "alias -L; typeset -f"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
			// Pin ZDOTDIR to the real HOME. An ambient ZDOTDIR (this plugin's own
			// shim, inherited by a nested shell or a test runner) would otherwise
			// make zsh read the shim's rc — a feedback loop that regenerates the
			// old state instead of the user's rc.
			env: { ...process.env, ZDOTDIR: home() },
			timeout: 20_000,
		});
	} catch {
		// No zsh on PATH (or it failed): leave the state absent, so the shim
		// sources nothing and the shell behaves exactly as before. Fail open.
		return false;
	}

	const temporary = `${state}.tmp`;
	writeFileSync(
		temporary,
		`# Generated by opencode-shell-rc. Do not edit.\n${output}\n`,
	);
	renameSync(temporary, state);
	compile(state);
	return true;
}

/**
 * `zcompile` the state so sourcing it costs ~0.5ms instead of ~10ms (zsh reads
 * `state.zsh.zwc` automatically when it is newer than the source). Best effort:
 * on failure the plain text is still sourced.
 */
function compile(state: string): void {
	try {
		rmSync(`${state}.zwc`, { force: true });
		execFileSync("zsh", ["-c", 'zcompile "$1"', "zsh", state], {
			stdio: ["ignore", "ignore", "ignore"],
			env: { ...process.env, ZDOTDIR: home() },
			timeout: 20_000,
		});
	} catch {
		// leftover text-only state is still correct, just slower to source
	}
}

/**
 * Idempotently lay down the shim, the rc symlinks and a fresh state file. Cheap
 * (a small read plus a few stats) so it is safe to call before every command.
 */
export function prepare(): void {
	mkdirSync(stateDir(), { recursive: true });

	const shim = shimFile();
	const content = shimContent();
	if (!existsSync(shim) || readFileSync(shim, "utf8") !== content) {
		writeFileSync(shim, content);
	}

	for (const name of LINKED) {
		const source = join(home(), name);
		if (!existsSync(source)) continue;
		const link = join(stateDir(), name);
		try {
			lstatSync(link);
			continue; // already there (symlink or file) — never clobber
		} catch {
			// absent: link it
		}
		try {
			symlinkSync(source, link);
		} catch {
			// best effort; a missing link only affects nested interactive shells
		}
	}

	refreshIfStale();
}
